Creating an account and logging into your account
mollymaefraser/5COM1079-SDE-backend pull request #34
Opened 2023-08-23 09:41 UTC by eleanorwarren

2023-08-23 11:55 UTC, developer-t0m requested changes
good start - a few comments to get this all wrapped up

2023-08-23 11:55 UTC, developer-t0m commented on src/Meditelligence.DTOs/Read/UserReadDto.cs
> +        //History is not yet included and needs to be reviewed
note, you won't need to bother with the history - the bit I'm writing now will mean all that is needed is a UserID

which leads me onto this point -> can you add UserID to this readDTO please.

2023-08-23 11:55 UTC, developer-t0m commented on src/Meditelligence.DataAccess/Repositories/IUserRepo.cs
> +
might be worth having another method here -> GetUserByEmailAndPassword, or something along those lines. 

The reason being is for login, you'll be wanting an email and password, and want to retrieve the user account based on those two parameters.

Question as well -> are you hashing the password that comes in for registration?

2023-08-23 11:55 UTC, developer-t0m commented on src/Meditelligence.DataAccess/Repositories/UserRepo.cs
> +
Implement GetUserByEmailPassword as discussed in previous comment

2023-08-23 11:55 UTC, developer-t0m commented on src/Meditelligence.Models/Meditelligence.Models.csproj
> +    <ProjectReference Include="..\Meditelligence.DTOs\Meditelligence.DTOs.csproj" />
this project reference shouldn't be needed?

2023-08-23 11:55 UTC, developer-t0m commented on src/Meditelligence.WebAPI/Controllers/UserController.cs
> +
Don't need the GetAllUsers endpoint -> there won't be a use case for that.

You do however need the registration endpoint and the login endpoint, as well as a delete account endpoint.

2023-08-23 14:10 UTC, eleanorwarren commented on src/Meditelligence.DataAccess/Repositories/IUserRepo.cs
> +
Not hashing no

2023-08-23 18:50 UTC, developer-t0m requested changes
quite a few changes - as you've mentioned, might still be a little bit of confusion re. what we are doing on the API side. Remember the website will send us information, it's up to us in these methods to process them for our designed use case.

2023-08-23 18:50 UTC, developer-t0m commented on src/Meditelligence.DataAccess/Repositories/UserRepo.cs
> +        public bool UserLogIn(bool isAdmin)
you don't need this method - as the boolean value is returned via the login endpoint anyway

2023-08-23 18:50 UTC, developer-t0m commented on src/Meditelligence.DataAccess/Repositories/UserRepo.cs
> +        public IEnumerable<User> CreateUser()
this method technically is just creating a blank record? you need to pass a User object into the method via parameter, and then you add this to the database

2023-08-23 18:50 UTC, developer-t0m commented on src/Meditelligence.DataAccess/Repositories/UserRepo.cs
> +        public IEnumerable<User> CreateUser()
and also, why are you returning a list of Users? this should be a void method.
Also, you haven't done any check to see if the record already exists -> this can be done by checking if a record exists with the same email.

the final statement should just be _context.Users.Add(user)

2023-08-23 18:50 UTC, developer-t0m commented on src/Meditelligence.WebAPI/Controllers/UserController.cs
> +        public IActionResult UserLogIn(bool isAdmin)
remember what I said before - when a user attempts a login, we will take in an email and password.

The return type from our method should be ActionResult<UserReadDto>

2023-08-23 18:50 UTC, developer-t0m commented on src/Meditelligence.WebAPI/Controllers/UserController.cs
> +        public IActionResult UserLogIn(bool isAdmin)
remember as well you've got a method in the repo that finds a user based on email and password - and it can return null or the record.

2023-08-27 22:18 UTC, developer-t0m requested changes
Missing a lot of functionality here - if you would like me to help, please reach out.

2023-08-27 22:18 UTC, developer-t0m commented on src/Meditelligence.DataAccess/Repositories/IUserRepo.cs
> +
we should be hashing the password as a bare minimum during registration

2023-08-27 22:18 UTC, developer-t0m commented on src/Meditelligence.WebAPI/Controllers/UserController.cs
> +
Missing endpoints here - need one for registration and login.

2023-08-27 22:18 UTC, developer-t0m commented on src/Meditelligence.DataAccess/Repositories/UserRepo.cs
> +        }
This DeleteUser record is wrong - why are you returning a casted list of a remove method? it should be void 

Additionally - you're not actually deleting anything here. You're creating a new User object, then removing that? It doesn't even exist in the database.

A user object should be passed into the method here. You also do not need the attach method at all.

2023-08-28 12:08 UTC, developer-t0m commented
Final changes to be addressed by @developer-t0m

2023-08-28 12:08 UTC, developer-t0m approved these changes

2023-08-28 12:09 UTC, merged